---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: content/_index.md
  label: Homepage
- type: heading
  label: Blog Post
- type: directory
  path: content/blog
  label: Post
  create: all
  match: "**/*"
  templates:
  - post
- type: heading
  label: Author
- type: directory
  path: content/author
  label: Author
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Project
- type: directory
  path: content/project
  label: Project
  create: all
  match: "**/*"
  templates:
  - project
- type: heading
  label: Other Pages
- type: directory
  path: content
  label: Other Pages
  create: all
  match: "*"
  exclude: _index.md
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Configuration
- type: directory
  path: ''
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.83.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.83.1
